namespace Fistnet.Genepool.GodotViewer;

public partial class BoardView3D
{
    // These textures are generated by the GPU from stable display seeds. They never consume simulation randomness.
    private const string GroundShader = """
        shader_type spatial;
        render_mode unshaded, cull_disabled;
        uniform float cell_pixels = 8.0;
        varying vec4 cell_data;
        void vertex() { cell_data = INSTANCE_CUSTOM; }
        float hash(vec2 p) { return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453); }
        float noise(vec2 p) {
            vec2 i = floor(p); vec2 f = fract(p); f = f*f*(3.0-2.0*f);
            return mix(mix(hash(i),hash(i+vec2(1.0,0.0)),f.x),
                mix(hash(i+vec2(0.0,1.0)),hash(i+vec2(1.0,1.0)),f.x),f.y);
        }
        float segment(vec2 p, vec2 a, vec2 b) {
            vec2 v = b-a; return length(p-a-v*clamp(dot(p-a,v)/dot(v,v),0.0,1.0));
        }
        void fragment() {
            float detail = smoothstep(10.0,22.0,cell_pixels);
            vec2 p = UV + cell_data.y*29.0;
            float grain = noise(p*39.0)*0.12 + noise(p*11.0)*0.13 + noise(p*3.0)*0.11;
            vec3 soil = COLOR.rgb * (0.81+grain*detail);
            float amount = cell_data.x;
            float grass_patch = smoothstep(0.64-amount*0.46,0.89-amount*0.43,noise(p*5.0));
            soil = mix(soil,soil*vec3(0.81,1.12,0.78),grass_patch*amount*detail*0.45);
            float blade = 0.0;
            if (cell_pixels > 18.0 && amount > 0.1) {
                // Small reusable grass fans, their number determined by food quantity alone.
                for (int n=0; n<5; n++) {
                    float k=float(n); float h=hash(vec2(k+cell_data.y*73.0,3.0));
                    vec2 base=vec2(0.12+0.76*h,0.21+0.63*hash(vec2(k,cell_data.y*51.0)));
                    float enabled=step((k+0.7)/5.0,amount);
                    float length_blade=0.045+0.038*h;
                    for (int b=0; b<3; b++) {
                        float side=float(b)-1.0;
                        vec2 end=base+vec2(side*0.045,-length_blade*(1.0-abs(side)*0.22));
                        float d=segment(UV,base,end);
                        blade=max(blade,(1.0-smoothstep(0.004,0.014,d))*enabled);
                    }
                }
            }
            soil=mix(soil,vec3(0.48,0.57,0.20),blade*detail*0.78);
            float seam=min(min(UV.x,1.0-UV.x),min(UV.y,1.0-UV.y));
            float seam_width=0.5/max(cell_pixels,1.0);
            float grid=(1.0-smoothstep(seam_width,seam_width*2.2,seam))*smoothstep(13.0,25.0,cell_pixels);
            ALBEDO=soil*(1.0-grid*0.28);
        }
        """;

    private const string ColonyShader = """
        shader_type spatial;
        render_mode unshaded, cull_disabled, depth_prepass_alpha;
        uniform float cell_pixels = 8.0;
        varying vec4 colony_data;
        void vertex() { colony_data = INSTANCE_CUSTOM; }
        float hash(vec2 p) { return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453); }
        float noise(vec2 p) {
            vec2 i=floor(p); vec2 f=fract(p); f=f*f*(3.0-2.0*f);
            return mix(mix(hash(i),hash(i+vec2(1.0,0.0)),f.x),
                mix(hash(i+vec2(0.0,1.0)),hash(i+vec2(1.0,1.0)),f.x),f.y);
        }
        void fragment() {
            vec2 p=UV*2.0-1.0;
            float radius=length(p);
            float angle=atan(p.y,p.x);
            float phase=colony_data.x*37.0;
            float detail=smoothstep(9.0,18.0,cell_pixels);
            float lobes=0.060*sin(angle*5.0+phase)+0.045*sin(angle*9.0-phase*1.7)+0.023*sin(angle*17.0+phase);
            float body=0.60+lobes*detail;
            float rough=noise(p*43.0+phase)*0.032*detail;
            float hair=pow(max(0.0,sin(angle*67.0+sin(angle*19.0+phase)*2.0+phase)),8.0);
            float fringe=0.035+hair*0.10;
            float distance=radius-body-rough;
            // Screen derivatives preserve the edge at different perspective depths without bleaching tiny bodies.
            float aa=max(0.004,fwidth(distance)*0.6);
            float alpha=1.0-smoothstep(fringe*detail-aa,fringe*detail+aa,distance);
            if(alpha<0.025) { discard; }
            float colony_grain=noise(p*20.0+phase)*0.10+noise(p*65.0-phase)*0.07;
            vec3 color=COLOR.rgb*(0.93+colony_grain*detail);
            // Keep the existing flat branching mat. Veins retain its hue instead of turning the colony chalk-white.
            float branch=abs(sin(angle*13.0+sin(radius*27.0+phase)*0.55+phase));
            float veins=(1.0-smoothstep(0.035,0.12,branch))*smoothstep(0.18,0.60,radius)*detail;
            vec3 living_fringe=min(COLOR.rgb*1.08,vec3(1.0));
            color=mix(color,living_fringe,veins*0.30);
            float rim=smoothstep(-0.10,0.035,distance)*detail;
            color=mix(color,living_fringe,rim*0.22);
            float micro=noise(p*80.0+phase);
            color=mix(color,color*0.72,smoothstep(0.77,0.92,micro)*detail*0.32);
            // A thin irregular fringe separates the silhouette without replacing the inherited RGB colour.
            // Dark DNA keeps a black/dark interior with a pale edge; lighter DNA receives a dark edge.
            // At overview scale an approximately one-pixel edge remains visible even when the RGB
            // matches the ground. Tiny dots share that pixel with their core; close views retain a thin fringe.
            float outer_distance=distance-fringe*detail;
            float close_edge_width=min(0.085,max(0.018,aa*1.5));
            float overview_edge_width=min(0.60,max(0.12,aa*2.0));
            float edge_width=mix(overview_edge_width,close_edge_width,detail);
            float edge=smoothstep(-edge_width-aa*0.45,-edge_width+aa*0.45,outer_distance);
            float luminance=dot(COLOR.rgb,vec3(0.2126,0.7152,0.0722));
            vec3 edge_color=luminance<0.12 ? vec3(0.82,0.87,0.87) : COLOR.rgb*0.10;
            color=mix(color,edge_color,edge*mix(0.98,0.90,detail));
            // Choose the edge from the original RGB, then dim the entire unmatched colony consistently.
            // Otherwise dimming a medium-dark colour can incorrectly switch its edge to bright pale.
            ALBEDO=color*colony_data.y;
            ALPHA=alpha;
        }
        """;
}
