"""Seed capsule installer. Python 3.11+, standard library, no network.

Generated by Other. Only explicitly requested installation/verification is allowed.
This module is stored once, compressed in the distribution's verified ZIP.
"""
from __future__ import annotations

import argparse
import base64
import hashlib
import io
import json
import os
from pathlib import Path
import re
import stat
import sys
from datetime import datetime, timezone
import zipfile

PAYLOAD_BEGIN = b"<!-- SEED_PAYLOAD_BEGIN -->\n"
PAYLOAD_END = b"\n<!-- SEED_PAYLOAD_END -->"
MAX_CAPSULE = 4 * 1024 * 1024
MAX_EXPANDED = 8 * 1024 * 1024
MAX_FILES = 100
GENERATED = {".SeedAnalyzer/package-manifest.json", ".SeedAnalyzer/installation.json",
             "KnowledgeBase/core.json", "KnowledgeBase/records.jsonl", "KnowledgeBase/sources.json"}


class InstallError(Exception):
    pass


def require(condition, message):
    if not condition:
        raise InstallError(message)


def digest(data):
    return hashlib.sha256(data).hexdigest().upper()


def json_bytes(value):
    return (json.dumps(value, ensure_ascii=False, sort_keys=True, indent=2) + "\n").encode("utf-8")


def no_duplicate_keys(pairs):
    result = {}
    for key, value in pairs:
        require(key not in result, f"Duplicate JSON key: {key}")
        result[key] = value
    return result


def parse_json(data):
    return json.loads(data, object_pairs_hook=no_duplicate_keys)


def checked_path(path):
    """Reject links/reparse points in every existing lexical ancestor."""
    absolute = Path(os.path.abspath(path))
    for part in reversed((absolute, *absolute.parents)):
        try:
            info = part.lstat()
        except FileNotFoundError:
            continue
        require(not stat.S_ISLNK(info.st_mode) and not getattr(info, "st_file_attributes", 0) & 0x400,
                f"Linked/reparse path is not allowed: {part}")
    return absolute.resolve()


def regular_bytes(path, maximum=MAX_EXPANDED):
    path = checked_path(path)
    require(path.is_file(), f"Expected a regular file: {path}")
    require(path.stat().st_size <= maximum, f"File exceeds size limit: {path}")
    data = path.read_bytes()
    require(len(data) <= maximum, f"File grew beyond size limit: {path}")
    return data


def valid_member(name):
    require(isinstance(name, str) and len(name) <= 200, "Invalid archive path")
    require(re.fullmatch(r"[A-Za-z0-9_./-]+", name) is not None, f"Unsupported path: {name}")
    parts = name.split("/")
    require(all(p not in ("", ".", "..") and not p.endswith((".", " ")) for p in parts),
            f"Unsafe archive path: {name}")
    reserved = {"CON", "PRN", "AUX", "NUL", *(f"COM{i}" for i in range(1, 10)),
                *(f"LPT{i}" for i in range(1, 10))}
    require(all(p.split(".")[0].upper() not in reserved for p in parts), f"Reserved path: {name}")
    require(name == "AGENTS.md" or (len(parts) > 1 and parts[0] in (".SeedAnalyzer", "KnowledgeBase")),
            f"Undeclared install surface: {name}")
    require(name not in GENERATED, f"Archive shadows generated state: {name}")
    return name


def read_capsule(path):
    raw = regular_bytes(path, MAX_CAPSULE)
    envelope = raw.replace(b"\r\n", b"\n")
    require(envelope.count(PAYLOAD_BEGIN) == envelope.count(PAYLOAD_END) == 1, "Missing/duplicate payload markers")
    header, rest = envelope.split(PAYLOAD_BEGIN)
    encoded, tail = rest.split(PAYLOAD_END)
    require(not tail.strip(), "Unexpected content after payload")
    hashes = re.findall(rb"(?m)^Payload-SHA256: ([A-F0-9]{64})$", header)
    require(len(hashes) == 1, "Missing/duplicate payload SHA-256")
    require(re.fullmatch(rb"[A-Za-z0-9+/=\r\n]+", encoded) is not None, "Invalid Base64 alphabet")
    packed = base64.b64decode(encoded.replace(b"\r", b"").replace(b"\n", b""), validate=True)
    require(digest(packed).encode() == hashes[0], "Payload SHA-256 mismatch")
    with zipfile.ZipFile(io.BytesIO(packed)) as archive:
        entries = archive.infolist()
        require(1 < len(entries) <= MAX_FILES + 1, "Unexpected ZIP file count")
        require(sum(e.file_size for e in entries) <= MAX_EXPANDED, "Expanded size limit exceeded")
        seen = set()
        for entry in entries:
            name = entry.filename
            require(name == "manifest.json" or valid_member(name), f"Invalid member: {name}")
            require(name.casefold() not in seen, f"Duplicate/case-colliding member: {name}")
            seen.add(name.casefold())
            require(not entry.is_dir() and not entry.flag_bits & 1, "Directories/encryption not supported")
            mode = entry.external_attr >> 16
            require(stat.S_IFMT(mode) in (0, stat.S_IFREG), f"Special/link ZIP member: {name}")
            require(entry.compress_type in (zipfile.ZIP_STORED, zipfile.ZIP_DEFLATED), "Unsupported compression")
            require(entry.file_size <= max(1, entry.compress_size) * 300, "Suspicious expansion ratio")
        require("manifest.json" in seen, "Missing manifest")
        manifest_raw = archive.read("manifest.json")
        manifest = parse_json(manifest_raw)
        require(manifest.get("format") == 1, "Unsupported manifest format")
        specs = manifest.get("files")
        require(isinstance(specs, dict) and 1 <= len(specs) <= MAX_FILES, "Invalid manifest file list")
        require(set(specs) == {e.filename for e in entries} - {"manifest.json"}, "Manifest/ZIP set mismatch")
        files = {}
        for name, expected in specs.items():
            valid_member(name)
            require(not any(name.startswith(other + "/") for other in specs if other != name), "File/directory collision")
            data = archive.read(name)
            require(expected == {"bytes": len(data), "sha256": digest(data)}, f"Manifest mismatch: {name}")
            files[name] = data
    mandatory = {"AGENTS.md", ".SeedAnalyzer/CONSTITUTION.md", ".SeedAnalyzer/KB.md",
                 ".SeedAnalyzer/installer.py", "KnowledgeBase/tools/kb.py", "KnowledgeBase/tools/prepare.py",
                 "KnowledgeBase/tools/kb_client.py", "KnowledgeBase/tools/consolidation_scope.py"}
    require(mandatory <= files.keys(), "Missing mandatory package files")
    return raw, digest(packed), manifest, manifest_raw, files


def initial_state(target, timestamp):
    records = b""
    sources = json_bytes({"catalog_revision": 1, "sources": []})
    core = {
        "schema_version": 1, "kb_revision": 1, "updated_at": timestamp,
        "experiment": {"root": str(target), "status": "unbound", "purpose": None,
                       "root_semantics": "Mechanical installation boundary; owner activation still required."},
        "pinned_record_ids": [], "routes": {}, "owner_decision_ids": [], "open_question_ids": [],
        "next_decision_order": [],
        "state_files": {"records_jsonl_sha256": digest(records), "sources_json_sha256": digest(sources)},
    }
    return {"KnowledgeBase/core.json": json_bytes(core), "KnowledgeBase/records.jsonl": records,
            "KnowledgeBase/sources.json": sources}


def expected_install(target, capsule_raw, zip_hash, manifest, manifest_raw, files, timestamp):
    runtime = initial_state(target, timestamp)
    receipt = {
        "format": 1, "package_id": manifest["package_id"], "payload_sha256": zip_hash,
        "capsule_sha256": digest(capsule_raw), "manifest_sha256": digest(manifest_raw),
        "installation_root": str(target), "installed_at": timestamp,
        "experiment_activation": "not performed", "kb_revision_at_install": 1,
        "initial_state": {name: {"sha256": digest(data), "bytes": len(data)} for name, data in runtime.items()},
    }
    return {**files, **runtime, ".SeedAnalyzer/package-manifest.json": manifest_raw,
            ".SeedAnalyzer/installation.json": json_bytes(receipt)}


def tree_files(root):
    root = checked_path(root)
    require(root.is_dir(), f"Expected directory: {root}")
    found = set()
    for directory, dirs, names in os.walk(root, followlinks=False):
        for name in dirs + names:
            path = checked_path(Path(directory) / name)
            require(path.is_file() or path.is_dir(), f"Special file: {path}")
        for name in names:
            found.add((Path(directory) / name).relative_to(root).as_posix())
    return found


def verify_tree(root, expected):
    require(tree_files(root) == set(expected), f"Unexpected/missing files in {root}")
    for name, data in expected.items():
        require(regular_bytes(root / name) == data, f"Content collision: {root / name}")


def stage_write(stage, relative, data):
    dest = checked_path(stage / relative)
    require(dest.is_relative_to(stage), "Stage path escaped")
    if dest.exists():
        require(regular_bytes(dest) == data, f"Stage collision: {dest}")
        return
    dest.parent.mkdir(parents=True, exist_ok=True)
    with dest.open("xb") as handle:
        handle.write(data)
        handle.flush()
        os.fsync(handle.fileno())


def verify_installed(target):
    target = checked_path(target)
    checked_path(target / "AGENTS.override.md")
    require(not (target / "AGENTS.override.md").exists(), "AGENTS.override.md conflicts with the entry point")
    receipt = parse_json(regular_bytes(target / ".SeedAnalyzer/installation.json"))
    require(receipt.get("installation_root") == str(target), "Installation has moved; root binding needs explicit migration")
    raw = regular_bytes(target / ".SeedAnalyzer/package-manifest.json")
    require(digest(raw) == receipt["manifest_sha256"], "Installed manifest identity mismatch")
    manifest = parse_json(raw)
    require(manifest.get("package_id") == receipt.get("package_id"), "Package identity mismatch")
    for name, expected in manifest["files"].items():
        valid_member(name)
        data = regular_bytes(target / name)
        require(expected == {"bytes": len(data), "sha256": digest(data)}, f"Installed file changed: {name}")
    core = parse_json(regular_bytes(target / "KnowledgeBase/core.json"))
    require(core.get("schema_version") == 1 and core.get("experiment", {}).get("root") == str(target), "Invalid KB binding/schema")
    require(type(core.get("kb_revision")) is int and core["kb_revision"] > 0, "Invalid KB revision")
    for filename, key in (("records.jsonl", "records_jsonl_sha256"), ("sources.json", "sources_json_sha256")):
        require(digest(regular_bytes(target / "KnowledgeBase" / filename, 256 * 1024 * 1024)) == core["state_files"][key],
                f"KB state hash mismatch: {filename}")
    return {"status": "PASS", "operation": "verify", "package_id": manifest["package_id"],
            "static_files_verified": len(manifest["files"]), "kb_revision": core["kb_revision"],
            "verification_scope": "Static package bytes and KB root/state hashes; no source reads or agent-boot proof.",
            "receipt": receipt}


def cleanup_stage(stage, permitted):
    """Delete only a preflighted installer's exact staging tree, never arbitrary trees."""
    actual = tree_files(stage)
    require(actual <= permitted, f"Unexpected stage content; retained for inspection: {stage}")
    # Keep the recovery journal last; completed-install recovery also tolerates its absence.
    ordered = sorted(actual - {"journal.json", "capsule.backup"})
    ordered += [n for n in ("capsule.backup", "journal.json") if n in actual]
    paths = [checked_path(stage / name) for name in ordered]
    require(all(p.is_relative_to(stage) for p in paths), "Cleanup escaped staging root")
    for path in paths:
        path.unlink()
    directories = sorted((p for p in stage.rglob("*") if p.is_dir()), key=lambda p: len(p.parts), reverse=True)
    for directory in directories:
        checked_path(directory).rmdir()
    stage.rmdir()


def install(capsule, target, resume=False):
    require(sys.version_info >= (3, 11), "Python 3.11 or later is required")
    target = checked_path(target)
    require(target.is_dir(), "Destination must already exist and be explicitly selected")
    for name in ("AGENTS.md", "AGENTS.override.md", ".SeedAnalyzer", "KnowledgeBase"):
        checked_path(target / name)
    require(not (target / "AGENTS.override.md").exists(), "AGENTS.override.md conflicts with the entry point")
    if checked_path(capsule) == target / "AGENTS.md" and (target / ".SeedAnalyzer/installation.json").exists():
        if PAYLOAD_BEGIN not in regular_bytes(capsule, MAX_CAPSULE).replace(b"\r\n", b"\n"):
            require(not resume, "Resume finalization using the original distribution capsule, not the installed entry point")
            result = verify_installed(target)
            return {**result, "operation": "already_installed", "writes": False}
    raw, zip_hash, manifest, manifest_raw, files = read_capsule(capsule)
    require(not (target / "AGENTS.override.md").exists(), "AGENTS.override.md conflicts with the entry point")
    stage = target / (".seed-install-stage-" + zip_hash[:16].lower())
    entry = target / "AGENTS.md"
    receipt_path = target / ".SeedAnalyzer/installation.json"
    if not stage.exists() and receipt_path.exists():
        result = verify_installed(target)
        require(result["receipt"]["capsule_sha256"] == digest(raw), "A different capsule is already installed")
        return {**result, "operation": "already_installed", "writes": False}
    if stage.exists():
        require(resume, f"Interrupted installation retained at {stage}; inspect and rerun with --resume")
        checked_path(stage)
    else:
        require(not resume, "No matching interrupted installation exists")
        for name in (".SeedAnalyzer", "KnowledgeBase"):
            require(not (target / name).exists(), f"Destination collision: {target / name}")
        if entry.exists():
            require(regular_bytes(entry, MAX_CAPSULE) == raw, "AGENTS.md contains different content")
    lock = checked_path(target / ".seed-install.lock")
    try:
        lock_handle = lock.open("x", encoding="utf-8")
    except FileExistsError:
        raise InstallError("Installer lock exists. Do not retry concurrently. After a hard kill, verify its process is gone before explicitly removing the stale lock.")
    try:
        with lock_handle:
            lock_handle.write(json.dumps({"pid": os.getpid(), "payload_sha256": zip_hash, "root": str(target)}))
            lock_handle.flush()
            if stage.exists() and receipt_path.exists():
                try:
                    finished = verify_installed(target)
                except (InstallError, OSError, ValueError, KeyError, TypeError):
                    finished = None
                if finished is not None:
                    receipt = finished["receipt"]
                    require(receipt["capsule_sha256"] == digest(raw), "Recovery capsule differs from installed package")
                    expected = expected_install(target, raw, zip_hash, manifest, manifest_raw, files, receipt["installed_at"])
                    journal = {"format": 1, "root": str(target), "payload_sha256": zip_hash,
                               "capsule_sha256": digest(raw), "timestamp": receipt["installed_at"]}
                    residue = {**expected, "journal.json": json_bytes(journal), "capsule.backup": raw}
                    actual = tree_files(stage)
                    require(actual <= residue.keys(), "Unexpected finalization residue")
                    for name in actual:
                        require(regular_bytes(stage / name) == residue[name], f"Changed recovery residue: {name}")
                    cleanup_stage(stage, set(residue))
                    return {**finished, "operation": "resumed_finalization", "stop": True}
            if not stage.exists():
                stage.mkdir()
                journal = {"format": 1, "root": str(target), "payload_sha256": zip_hash,
                           "capsule_sha256": digest(raw), "timestamp": datetime.now(timezone.utc).isoformat()}
                stage_write(stage, "journal.json", json_bytes(journal))
            else:
                journal = parse_json(regular_bytes(stage / "journal.json"))
                require(journal["root"] == str(target) and journal["payload_sha256"] == zip_hash
                        and journal["capsule_sha256"] == digest(raw), "Recovery journal identity mismatch")
            expected = expected_install(target, raw, zip_hash, manifest, manifest_raw, files, journal["timestamp"])
            allowed = set(expected) | {"journal.json", "capsule.backup"}
            require(tree_files(stage) <= allowed, "Unexpected files in recovery stage")
            stage_write(stage, "capsule.backup", raw)
            for name, data in expected.items():
                stage_write(stage, name, data)
            for top in (".SeedAnalyzer", "KnowledgeBase"):
                subset = {name[len(top) + 1:]: data for name, data in expected.items() if name.startswith(top + "/")}
                verify_tree(stage / top, subset)
                if (target / top).exists():
                    require(resume, f"Unexpected destination appeared: {top}")
                    verify_tree(target / top, subset)
                else:
                    os.rename(stage / top, target / top)
                    verify_tree(target / top, subset)
            require(not entry.exists() or regular_bytes(entry, MAX_CAPSULE) in (raw, expected["AGENTS.md"]), "Entry point changed during installation")
            # Recheck both promoted trees before removing the live distribution entry point.
            for name, data in expected.items():
                if name != "AGENTS.md":
                    require(regular_bytes(target / name) == data, f"Post-install mismatch: {name}")
            if not entry.exists() or regular_bytes(entry, MAX_CAPSULE) != expected["AGENTS.md"]:
                os.replace(stage / "AGENTS.md", entry)
            result = verify_installed(target)
            cleanup_stage(stage, allowed)
            return {**result, "operation": "installed", "experiment_activation": "not performed", "stop": True}
    finally:
        # Hard process termination can leave this lock; that is a deliberate stop gate.
        checked_path(lock).unlink()


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--capsule", type=Path)
    parser.add_argument("--target", type=Path, required=True)
    parser.add_argument("--resume", action="store_true")
    parser.add_argument("--verify", action="store_true")
    args = parser.parse_args(argv)
    try:
        if args.verify:
            require(not args.resume and args.capsule is None, "--verify does not take --capsule/--resume")
            result = verify_installed(args.target)
        else:
            require(args.capsule is not None, "Installation requires --capsule")
            result = install(args.capsule, args.target, args.resume)
        result.pop("receipt", None)
        print(json.dumps(result, ensure_ascii=False, indent=2))
        return 0
    except (InstallError, OSError, ValueError, KeyError, TypeError, zipfile.BadZipFile, EOFError) as exc:
        print(json.dumps({"status": "FAIL", "error": str(exc), "rollback_claimed": False,
                          "recovery": "Inspect exact destination/stage. Capsule backup is retained through replacement, then removed during final cleanup. Use the original distribution for --resume; a hard-kill lock requires explicit inspection. No automatic retry."}, indent=2))
        return 1


if __name__ == "__main__":
    sys.exit(main())
